replicaCount: 1

image:
  repository: localhost:32000/my-django-app
  tag: "latest"

service:
  type: NodePort #ClusterIP
  port: 80
  targetPort: 80
  nodePort: 30400

ingress:
  enabled: false

resources: {}


serviceAccount:
  create: true
  name: ""

autoscaling:
  create: false
